image: node:lts-trixie

stages:
  - build
  - pages

build:
  stage: build
  script:
    - npm install
    - npm run format:check
    - npm run lint
    - npm run type-check
    - npm run build-only -- --base "/viewer/" --outDir public

  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: pages
  script:
    - echo "Publishing GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
