import type { ExtendedMapContext } from '@/types/map.types'
import type { MapLayer } from '@/utils/layer.utils'

/**
 * Default MapContext configuration for the map application
 * Contains OpenStreetMap as the base layer with a world view
 */
// export const DEFAULT_MAP_CONTEXT: ExtendedMapContext = {
//   layers: [
//     {
//       type: 'xyz',
//       id: 'basemap-osm',
//       url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
//       visibility: true,
//       opacity: 1,
//       label: 'OpenStreetMap',
//       attributions: '© OpenStreetMap contributors',
//       extras: {
//         basemap: true,
//       },
//     },
//     {
//       type: 'wms',
//       id: 'wms-population',
//       url: 'https://data.geopf.fr/wms-r/wms',
//       name: 'INSEE.FILOSOFI.POPULATION',
//       label: 'Population INSEE',
//       visibility: true,
//       clickable: false,
//       opacity: 0.7,
//       attributions: '© IGN - INSEE',
//       version: 0,
//     },
//     {
//       type: 'wfs',
//       id: 'wfs-bus-lines',
//       url: 'https://data.lillemetropole.fr/geoserver/dsp_ilevia/ows?REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0',
//       featureType: 'ilevia_traceslignes',
//       label: 'Lignes de bus Ilevia',
//       visibility: true,
//       opacity: 0.8,
//       attributions: '© MEL - Ilevia',
//       hoverable: true,
//       hoverStyle: FEATURE_HOVER_STYLE,
//       version: 0,
//     },
//     {
//       type: 'geojson',
//       id: 'geojson-bike-racks',
//       url: 'https://data.lillemetropole.fr/data/ogcapi/collections/roubaix:implantation_des_arceaux_velos_a_roubaix/items?f=geojson&limit=-1',
//       label: 'Arceaux vélos Roubaix',
//       visibility: false,
//       opacity: 1,
//       attributions: '© Ville de Roubaix',
//       hoverable: true,
//       hoverStyle: FEATURE_HOVER_STYLE,
//       version: 0,
//     },
//     {
//       type: 'stac',
//       url: 'https://stac-pg-api.ifremer.fr/collections/AVHRR_SST_METOP_B_OSISAF_L2P_v1_0',
//       id: 'AVHRR_SST_METOP_B_OSISAF_L2P_v1_0-no-collection-id',
//       visibility: false,
//     },
//     {
//       type: 'stac',
//       url: 'https://stacapi-cdos.apps.okd.crocc.meso.umontpellier.fr/collections/sentinel-2-radiometric-indices',
//       id: 'sentinel-2-radiometric-indices',
//       visibility: false,
//     },
//     // Alternative STAC layer configuration
//     // {
//     //   type: 'stac',
//     //   url: 'https://stac-pg-api.ifremer.fr',
//     //   collectionId: 'AVHRR_SST_METOP_B_OSISAF_L2P_v1_0',
//     //   id: 'AVHRR_SST_METOP_B_OSISAF_L2P_v1_0',
//     // },
//     {
//       type: 'geojson',
//       id: 'geojson-mock-urls',
//       data: {
//         type: 'FeatureCollection',
//         features: [
//           {
//             type: 'Feature',
//             id: 'poi-1',
//             geometry: { type: 'Point', coordinates: [3.06, 50.63] },
//             properties: {
//               name: 'Point avec URL HTTPS',
//               description: 'Voir documentation: https://example.com/docs',
//               website: 'https://www.openstreetmap.org',
//               contact: 'email@example.com',
//             },
//           },
//           {
//             type: 'Feature',
//             id: 'poi-2',
//             geometry: { type: 'Point', coordinates: [3.07, 50.625] },
//             properties: {
//               name: 'Point avec URL HTTP',
//               info: 'Source: http://data.example.org/api',
//               note: 'Protocole non sécurisé',
//             },
//           },
//           {
//             type: 'Feature',
//             id: 'poi-3',
//             geometry: { type: 'Point', coordinates: [3.05, 50.635] },
//             properties: {
//               name: 'Point avec URLs multiples',
//               links: 'Voir https://example.com et aussi https://another-site.org/page',
//               documentation: 'https://docs.example.com/guide',
//             },
//           },
//           {
//             type: 'Feature',
//             id: 'poi-4',
//             geometry: { type: 'Point', coordinates: [3.055, 50.62] },
//             properties: {
//               name: 'Point avec protocoles non-HTTP',
//               file_path: 'file:///home/user/data.txt',
//               ftp_server: 'ftp://files.example.com/data',
//               note: 'Ces URLs ne doivent PAS être cliquables',
//             },
//           },
//         ],
//       },
//       label: 'Points de test (URLs)',
//       visibility: true,
//       opacity: 1,
//       attributions: 'Mock data',
//       hoverable: true,
//       hoverStyle: FEATURE_HOVER_STYLE,
//       version: 0,
//     },
//     // COG (geoTiff) sample layers
//     {
//       type: 'geotiff',
//       id: 'cog-oam-brest',
//       url: 'https://oin-hotosm-temp.s3.us-east-1.amazonaws.com/66e43a1ecd0baa0001b62135/0/66e43a1ecd0baa0001b62136.tif',
//       label: 'COG Brest (OpenAerialMap)',
//       visibility: true,
//       opacity: 1,
//       attributions: '© OpenAerialMap contributors, CC-BY 4.0',
//       version: 0,
//     },
//     {
//       type: 'geotiff',
//       id: 'cog-sentinel2-tci',
//       url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/Q/WD/2020/7/S2A_36QWD_20200701_0_L2A/TCI.tif',
//       label: 'Sentinel-2 COG (TCI)',
//       visibility: false,
//       opacity: 1,
//       attributions: '© Copernicus Sentinel-2',
//       version: 0,
//     },
//     // ILICO layers
//     {
//       type: 'geojson',
//       id: 'ilico-points',
//       url: 'https://sextant.odatis-ocean.fr/services/wfs/ilico?service=WFS&request=GetFeature&typename=ILICO_points&outputFormat=GeoJSON',
//       label: 'ILICO Points',
//       visibility: true,
//       opacity: 1,
//       attributions: '© ODATIS / ILICO',
//       hoverable: true,
//       hoverStyle: FEATURE_HOVER_STYLE,
//       version: 0,
//     },
//     {
//       type: 'geojson',
//       id: 'ilico-surface',
//       url: 'https://sextant.odatis-ocean.fr/services/wfs/ilico?service=WFS&request=GetFeature&typename=ILICO_surface&outputFormat=GeoJSON',
//       label: 'ILICO Surface',
//       visibility: false,
//       opacity: 0.7,
//       attributions: '© ODATIS / ILICO',
//       hoverable: true,
//       hoverStyle: FEATURE_HOVER_STYLE,
//       version: 0,
//     },
//   ],
//   view: {
//     center: [3.0586, 50.6292],
//     zoom: 11,
//   },
// }
export const DEFAULT_BACKGROUND_LAYERS: MapLayer[] = [
  {
    type: 'xyz',
    id: 'basemap-osm',
    url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
    visibility: true,
    opacity: 1,
    label: 'OpenStreetMap',
    attributions: '© OpenStreetMap contributors',
  },
  {
    type: 'wmts',
    id: 'basemap-planign',
    url: 'https://data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities',
    name: 'GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2',
    visibility: false,
    opacity: 1,
    label: 'Plan IGN',
    attributions: '© IGN',
  },
  {
    type: 'wmts',
    id: 'basemap-bdortho',
    url: 'https://data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities',
    name: 'ORTHOIMAGERY.ORTHOPHOTOS',
    visibility: false,
    opacity: 1,
    label: 'BD ORTHO',
    attributions: '© IGN - BD ORTHO®',
  },
  {
    type: 'wmts',
    id: 'basemap-cadastre',
    url: 'https://data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities',
    name: 'CADASTRALPARCELS.PARCELS',
    visibility: false,
    opacity: 1,
    label: 'BS PARCELLLAIRE',
    attributions: '© IGN',
  },
  {
    type: 'wmts',
    id: 'basemap-relief',
    url: 'https://data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities',
    name: 'ELEVATION.SLOPES',
    visibility: false,
    opacity: 1,
    label: 'Relief',
    attributions: '© IGN',
  },
]

export const DEFAULT_MAP_CONTEXT: ExtendedMapContext = {
  layers: [],
  backgroundLayers: DEFAULT_BACKGROUND_LAYERS,
  view: {
    center: [3.0586, 50.6292],
    zoom: 11,
  },
}
